import {
	ZBookAsset,
	ZCreateCatalogBookDTO,
	ZCreateHighlightDTO,
	ZCreateLibraryBookDTO,
	ZHighlight,
	ZLibraryBookIDParams,
	ZLibraryCatalogListResponse,
	ZLibraryCatalogCreateResponse,
	ZLibraryDeleteResponse,
	ZLibraryHighlightIDParams,
	ZLibraryHighlightsResponse,
	ZLibraryListQuery,
	ZLibraryBooksListResponse,
	ZReadingState,
	ZReadingStatePathParams,
	ZUpdateHighlightDTO,
	ZUpdateLibraryBookDTO,
	ZUploadBookAssetDTO,
	ZUpsertReadingStateDTO,
	ZUserLibraryBook,
} from '@zeile/zod'
import { initContract } from '@ts-rest/core'
import { failResponses, getSecurityMetadata } from '../utils.js'

const c = initContract()
const metadata = getSecurityMetadata({ security: true, securityType: 'bearerOrCookie' })

export const libraryContract = c.router({
	createCatalogBook: {
		summary: 'Create catalog book',
		description: 'Create a catalog-level book record.',
		path: '/api/v1/library/catalog/books',
		method: 'POST',
		body: ZCreateCatalogBookDTO,
		responses: {
			201: ZLibraryCatalogCreateResponse,
			...failResponses,
		},
		metadata,
	},
	listCatalogBooks: {
		summary: 'List catalog books',
		description: 'List catalog books with pagination.',
		path: '/api/v1/library/catalog/books',
		method: 'GET',
		query: ZLibraryListQuery,
		responses: {
			200: ZLibraryCatalogListResponse,
			...failResponses,
		},
		metadata,
	},
	uploadAsset: {
		summary: 'Upload book asset',
		description: 'Upload and attach a file asset to a catalog book.',
		path: '/api/v1/library/assets/upload',
		method: 'POST',
		body: ZUploadBookAssetDTO,
		responses: {
			201: ZBookAsset,
			...failResponses,
		},
		metadata,
	},
	upsertLibraryBook: {
		summary: 'Upsert library book',
		description: 'Create or update current user library entry for a catalog book.',
		path: '/api/v1/library/books',
		method: 'POST',
		body: ZCreateLibraryBookDTO,
		responses: {
			201: ZUserLibraryBook,
			...failResponses,
		},
		metadata,
	},
	listLibraryBooks: {
		summary: 'List library books',
		description: 'List authenticated user library books.',
		path: '/api/v1/library/books',
		method: 'GET',
		query: ZLibraryListQuery,
		responses: {
			200: ZLibraryBooksListResponse,
			...failResponses,
		},
		metadata,
	},
	updateLibraryBook: {
		summary: 'Update library book',
		description: 'Update authenticated user library book fields.',
		path: '/api/v1/library/books/:id',
		method: 'PATCH',
		pathParams: ZLibraryBookIDParams,
		body: ZUpdateLibraryBookDTO,
		responses: {
			200: ZUserLibraryBook,
			...failResponses,
		},
		metadata,
	},
	deleteLibraryBook: {
		summary: 'Delete library book',
		description: 'Soft delete a user library book entry.',
		path: '/api/v1/library/books/:id',
		method: 'DELETE',
		pathParams: ZLibraryBookIDParams,
		responses: {
			200: ZLibraryDeleteResponse,
			...failResponses,
		},
		metadata,
	},
	getReadingState: {
		summary: 'Get reading state',
		description: 'Get reading state by mode for a library book.',
		path: '/api/v1/library/books/:id/reading-states/:mode',
		method: 'GET',
		pathParams: ZReadingStatePathParams,
		responses: {
			200: ZReadingState,
			...failResponses,
		},
		metadata,
	},
	upsertReadingState: {
		summary: 'Upsert reading state',
		description: 'Create or update reading state with conflict semantics.',
		path: '/api/v1/library/books/:id/reading-states/:mode',
		method: 'PUT',
		pathParams: ZReadingStatePathParams,
		body: ZUpsertReadingStateDTO,
		responses: {
			200: ZReadingState,
			...failResponses,
		},
		metadata,
	},
	listHighlights: {
		summary: 'List highlights',
		description: 'List highlights for a library book.',
		path: '/api/v1/library/books/:id/highlights',
		method: 'GET',
		pathParams: ZLibraryBookIDParams,
		responses: {
			200: ZLibraryHighlightsResponse,
			...failResponses,
		},
		metadata,
	},
	createHighlight: {
		summary: 'Create highlight',
		description: 'Create highlight for a library book.',
		path: '/api/v1/library/books/:id/highlights',
		method: 'POST',
		pathParams: ZLibraryBookIDParams,
		body: ZCreateHighlightDTO,
		responses: {
			201: ZHighlight,
			...failResponses,
		},
		metadata,
	},
	updateHighlight: {
		summary: 'Update highlight',
		description: 'Update a highlight.',
		path: '/api/v1/library/highlights/:highlightId',
		method: 'PATCH',
		pathParams: ZLibraryHighlightIDParams,
		body: ZUpdateHighlightDTO,
		responses: {
			200: ZHighlight,
			...failResponses,
		},
		metadata,
	},
	deleteHighlight: {
		summary: 'Delete highlight',
		description: 'Soft-delete a highlight.',
		path: '/api/v1/library/highlights/:highlightId',
		method: 'DELETE',
		pathParams: ZLibraryHighlightIDParams,
		responses: {
			200: ZLibraryDeleteResponse,
			...failResponses,
		},
		metadata,
	},
})
